name: byteme_digital_marketplace
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  provider: ^6.1.2
  flutter_slidable: ^4.0.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# Settingan buat bikin App Icon otomatis
flutter_icons:
  android: true
  ios: true
  # Menggunakan logo yang ada background putihnya
  image_path: "assets/images/logo1.png"

# Settingan buat bikin Splash Screen otomatis
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#FFFFFF" # Ini kunci agar di HP mode gelap background tetap putih!
  image: "assets/images/logo1.png"
  
  android_12:
    color: "#FFFFFF"
    color_dark: "#FFFFFF"
    image: "assets/images/logo1.png"